#!/bin/bash

echo
echo "Preparing demo, please wait..."
echo

tmpdir=$(mktemp -d /tmp/go.XXXXX)
trap "rm -rf $tmpdir" EXIT QUIT INT TERM

GOPATH=$tmpdir:$GOPATH
go get github.com/jhunt/sandbox
go get github.com/pborman/uuid

cd $(dirname ${BASH_SOURCE[0]})
go run ./answer/server.go
